### ISSUE TITLE
warzone2100 fails to build with openssl-1.1 (new API)

### ISSUE THREAD

**Issue by wzdev-ci** [Warzone2100/old-trac-import#4493]
`resolution_fixed` `type_bug`   |    by Polynomial-C

___

Trying to build warzone2100-3.2.1 on a fully up-to-date ~amd64 Gentoo Linux machine with openssl-1.1.0 being installed fails like this:

```
x86_64-pc-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I../..  -DYY_NO_INPUT -D_REENTRANT -I/usr/include/SDL2 -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DNDEBUG -DWZ_DATADIR="\"/usr/share/games/warzone2100\"" -DLOCALEDIR="\"/usr/share/locale\"" -I../.. -I../../3rdparty -I../../3rdparty/quesoglc -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5 -I/usr/include/qt5/QtScript -I/usr/include/qt5 -I/usr/include/qt5/QtCore -I/usr/include/qt5  -g -Wno-enum-compare -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wcast-align -Wwrite-strings -Wpointer-arith -Wno-format-security -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5 -I/usr/include/qt5/QtScript -I/usr/include/qt5 -I/usr/include/qt5/QtCore -I/usr/include/qt5 -march=native -mtune=native -O2 -pipe -fPIC -std=c++11 -fstack-protector -c -o crc.o crc.cpp
crc.cpp: In member function ‘EcKey::Key EcKey::toBytes(EcKey::Privacy) const’:
crc.cpp:338:28: error: invalid conversion from ‘int (*)(const EC_KEY*, unsigned char**) {aka int (*)(const ec_key_st*, unsigned char**)}’ to ‘int (*)(EC_KEY*, unsigned char**) {aka int (*)(ec_key_st*, unsigned char**)}’ [-fpermissive]
  case Public:  toBytesFunc = i2o_ECPublicKey;  break;
                            ^
make[2]: *** [Makefile:513: crc.o] Error 1
make[2]: Leaving directory '/var/tmp/portage/games-strategy/warzone2100-3.2.1/work/warzone2100-3.2.1/lib/framework'
make[1]: *** [Makefile:586: all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/games-strategy/warzone2100-3.2.1/work/warzone2100-3.2.1'
make: *** [Makefile:506: all] Error 2
```
openssl-1.1 comes with a new API whose changes can be found at https://wiki.openssl.org/index.php/1.1_API_Changes 

___
_Issue migrated from [trac:4493](https://developer.wz2100.net/ticket/4493) at 2022-04-16 12:36:01 -0700_
