### ISSUE TITLE
fails to build with GLEW 1.12.0

### ISSUE THREAD

**Issue by wzdev-ci** [Warzone2100/old-trac-import#4300]
`resolution_duplicate` `type_bug`   |    by pabs

___

warzone2100 fails to build with GLEW 1.12.0, it seems like the GLEW API has changed:

```
g++ -DHAVE_CONFIG_H -I. -I../..  -I/usr/include/libpng12    -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DNDEBUG -DWZ_DATADIR="\"/usr/share/games/warzone2100\"" -DLOCALEDIR="\"/usr/share/locale\"" -I../.. -I/usr/include/libdrm  -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtNetwork -I/usr/include/qt4 -I/usr/include/qt4/QtScript -I/usr/include/qt4 -I/usr/include/qt4/QtCore  -D_FORTIFY_SOURCE=2 -g -Wno-enum-compare -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wcast-align -Wwrite-strings -Wpointer-arith -Wno-format-security -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtNetwork -I/usr/include/qt4 -I/usr/include/qt4/QtScript -I/usr/include/qt4 -I/usr/include/qt4/QtCore  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -fstack-protector -c -o screen.o screen.cpp
screen.cpp: In function 'void screen_EnableMissingFunctions()':
screen.cpp:264:22: error: invalid conversion from 'PFNGLSHADERSOURCEARBPROC {aka void (*)(unsigned int, int, const char**, const int*)}' to 'PFNGLSHADERSOURCEPROC {aka void (*)(unsigned int, int, const char* const*, const int*)}' [-fpermissive]
   __glewShaderSource = __glewShaderSourceARB;
                      ^
Makefile:423: recipe for target 'screen.o' failed
```

___
_Issue migrated from [trac:4300](https://developer.wz2100.net/ticket/4300) at 2022-04-16 11:50:48 -0700_
